# Generated by Django 4.2.7 on 2023-11-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='game.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='game.publisher'),
        ),
    ]
