# Generated by Django 4.2.7 on 2023-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['-launch_date']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating']},
        ),
    ]
