# Generated by Django 4.2.7 on 2023-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
